modLoader="javafml"
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://cpsdisplay.github.io" #optional

logoFile="assets/cpsdisplay/textures/logo.png" #optional

credits="People who wanted this" #optional
# A text field displayed in the mod UI
authors="${mod_authors}"

displayTest="IGNORE_ALL_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''${mod_description}'''